FROM node:22-slim
WORKDIR /app

ENV COREPACK_ENABLE_STRICT=0

RUN npm install -g npm@latest

COPY . .

RUN npm install --legacy-peer-deps

WORKDIR /app/web
RUN npm install --legacy-peer-deps

# Build-time env vars for Next.js (required by env-schema validation)
ENV NEXT_PUBLIC_CB_ENVIRONMENT=prod
ENV NEXT_PUBLIC_CODEBUFF_APP_URL=https://codeai.coolify.codemods.com
ENV NEXT_PUBLIC_SUPPORT_EMAIL=support@codemods.com
ENV NEXT_PUBLIC_POSTHOG_API_KEY=dummy
ENV NEXT_PUBLIC_POSTHOG_HOST_URL=http://localhost:8000
ENV NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_dummy
ENV NEXT_PUBLIC_STRIPE_CUSTOMER_PORTAL=http://localhost:3000
ENV NEXT_PUBLIC_GOOGLE_SITE_VERIFICATION_ID=
ENV NEXT_PUBLIC_WEB_PORT=3000
ENV OPEN_ROUTER_API_KEY=dummy
ENV OPENAI_API_KEY=dummy
ENV ANTHROPIC_API_KEY=dummy
ENV FIREWORKS_API_KEY=dummy
ENV SERPER_API_KEY=dummy
ENV GRAVITY_API_KEY=dummy
ENV IPINFO_TOKEN=dummy
ENV SPUR_TOKEN=dummy
ENV PORT=3000
ENV DATABASE_URL=postgresql://dummy:dummy@localhost:5432/dummy
ENV CODEBUFF_GITHUB_ID=dummy
ENV CODEBUFF_GITHUB_SECRET=dummy
ENV NEXTAUTH_URL=http://localhost:3000
ENV NEXTAUTH_SECRET=dummy_at_least_32_chars_long_1234567890
ENV STRIPE_SECRET_KEY=sk_test_dummy
ENV STRIPE_WEBHOOK_SECRET_KEY=whsec_dummy
ENV STRIPE_TEAM_FEE_PRICE_ID=price_dummy
ENV STRIPE_SUBSCRIPTION_100_PRICE_ID=price_dummy
ENV STRIPE_SUBSCRIPTION_200_PRICE_ID=price_dummy
ENV STRIPE_SUBSCRIPTION_500_PRICE_ID=price_dummy
ENV LOOPS_API_KEY=dummy
ENV DISCORD_PUBLIC_KEY=dummy
ENV DISCORD_BOT_TOKEN=dummy
ENV DISCORD_APPLICATION_ID=dummy

RUN npx next build

EXPOSE 3000
CMD ["node", "node_modules/.bin/next", "start"]
